[2021-05-26 10:14:17,309] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-25T10:11:03.490225+00:00 [queued]>
[2021-05-26 10:14:17,339] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-25T10:11:03.490225+00:00 [queued]>
[2021-05-26 10:14:17,339] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-26 10:14:17,340] {taskinstance.py:1069} INFO - Starting attempt 1 of 2
[2021-05-26 10:14:17,340] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-26 10:14:17,360] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): to_Postgres> on 2021-05-25T10:11:03.490225+00:00
[2021-05-26 10:14:17,367] {standard_task_runner.py:52} INFO - Started process 110 to run task
[2021-05-26 10:14:17,373] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Kuwait_DAG', 'to_Postgres', '2021-05-25T10:11:03.490225+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/covid_dag.py', '--cfg-path', '/tmp/tmp5x28rnqb', '--error-file', '/tmp/tmpyx92w2jx']
[2021-05-26 10:14:17,373] {standard_task_runner.py:77} INFO - Job 21: Subtask to_Postgres
[2021-05-26 10:14:17,455] {logging_mixin.py:104} INFO - Running <TaskInstance: Kuwait_DAG.to_Postgres 2021-05-25T10:11:03.490225+00:00 [running]> on host 431e058b07b3
[2021-05-26 10:14:17,521] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=Kuwait_DAG
AIRFLOW_CTX_TASK_ID=to_Postgres
AIRFLOW_CTX_EXECUTION_DATE=2021-05-25T10:11:03.490225+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-25T10:11:03.490225+00:00
[2021-05-26 10:14:18,366] {python.py:118} INFO - Done. Returned value was: None
[2021-05-26 10:14:18,384] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=Kuwait_DAG, task_id=to_Postgres, execution_date=20210525T101103, start_date=20210526T101417, end_date=20210526T101418
[2021-05-26 10:14:18,429] {taskinstance.py:1246} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-26 10:14:18,473] {local_task_job.py:146} INFO - Task exited with return code 0
